---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04

suites:
- name: default
  data_bags_path:  "./test/data_bags"
  attributes:
    nodejs:
      install_method: "package"
  run_list:
    - "recipe[streammachine]"
- name: master
  data_bags_path:  "./test/data_bags"
  attributes:
    streammachine:
      version: "master"
    nodejs:
      install_method: "package"
  run_list:
    - "recipe[streammachine]"
- name: node4
  data_bags_path:  "./test/data_bags"
  attributes:
    streammachine:
      version: "master"
    nodejs:
      install_method: "package"
      repo: "https://deb.nodesource.com/node_4.x"
  run_list:
    - "recipe[streammachine]"

